import assert from 'node:assert/strict';
import { lonLatToTile, lonLatToTileFloat, lonLatToWorld, tileBounds, worldToLonLat } from '../src/geo.js';
const origin = [113.1214, 23.0218];
const point = [113.2930, 22.8062];
const world = lonLatToWorld(point[0], point[1], ...origin);
const round = worldToLonLat(world.x, world.z, ...origin);
assert.ok(Math.abs(round.lon - point[0]) < 1e-9);
assert.ok(Math.abs(round.lat - point[1]) < 1e-9);
const tile = lonLatToTile(origin[0], origin[1], 13);
const float = lonLatToTileFloat(origin[0], origin[1], 13);
assert.equal(tile.x, Math.floor(float.x));
assert.equal(tile.y, Math.floor(float.y));
const b = tileBounds(tile.x, tile.y, 13);
assert.ok(origin[0] >= b.west && origin[0] <= b.east);
assert.ok(origin[1] <= b.north && origin[1] >= b.south);
console.log('geo: PASS');
