import assert from 'node:assert/strict';
import fs from 'node:fs';
const index = fs.readFileSync('index.html', 'utf8');
const app = fs.readFileSync('src/stage2/main.js', 'utf8');
const worker = fs.readFileSync('src/stage2/workerSetup.js', 'utf8');
const bootstrap = fs.readFileSync('src/stage2/bootstrap.js', 'utf8');
const layer = fs.readFileSync('src/stage2/landmarkLayer.js', 'utf8');
const landmarks = fs.readFileSync('src/stage2/landmarks.js', 'utf8');
const config = fs.readFileSync('src/config.js', 'utf8');
assert.match(index, /佛山数字城市/);
assert.match(index, /mode2dBtn/);
assert.match(index, /mode3dBtn/);
assert.match(index, /legacyBtn/);
assert.match(index, /stage2\/bootstrap\.js/);
assert.match(bootstrap, /workerSetup/);
assert.match(worker, /setWorkerUrl/);
assert.match(worker, /maplibre-gl-worker\.mjs\?worker&url/);
assert.match(app, /\.\/legacy\.html/);
assert.match(app, /maplibre-gl/);
assert.match(app, /pmtiles:\/\//);
assert.match(app, /OpenFreeMap|OPENFREEMAP_STYLE/);
assert.match(app, /fill-extrusion/);
assert.match(app, /raster-dem/);
assert.match(app, /setTerrain/);
assert.match(app, /overture-building-2d/);
assert.match(app, /overture-building-3d/);
assert.match(app, /overture-road-line/);
assert.match(app, /overture-water-fill/);
assert.match(app, /overture-transportation/);
assert.match(app, /overture-base/);
assert.match(app, /foshan-imagery/);
assert.match(app, /dataset\.roadFeatures/);
assert.match(app, /dataset\.waterFeatures/);
assert.match(config, /transportation\.pmtiles/);
assert.match(config, /base\.pmtiles/);
assert.match(layer, /GLTFLoader/);
assert.match(layer, /MercatorCoordinate\.fromLngLat/);
assert.ok((landmarks.match(/model:'planned'/g) || []).length >= 10);
assert.doesNotMatch(app, /new THREE\.ExtrudeGeometry/);
console.log('stage2: PASS');
