import assert from 'node:assert/strict';
import fs from 'node:fs';
const index=fs.readFileSync('index.html','utf8');
const app=fs.readFileSync('src/stage2/main.js','utf8');
const layer=fs.readFileSync('src/stage2/landmarkLayer.js','utf8');
const landmarks=fs.readFileSync('src/stage2/landmarks.js','utf8');
assert.match(index,/佛山数字城市/);
assert.match(index,/mode2dBtn/);
assert.match(index,/mode3dBtn/);
assert.match(index,/legacyBtn/);
assert.match(app,/\.\/legacy\.html/);
assert.match(app,/maplibre-gl/);
assert.match(app,/pmtiles:\/\//);
assert.match(app,/OpenFreeMap|OPENFREEMAP_STYLE/);
assert.match(app,/fill-extrusion/);
assert.match(app,/raster-dem/);
assert.match(app,/setTerrain/);
assert.match(app,/overture-building-2d/);
assert.match(app,/overture-building-3d/);
assert.match(layer,/GLTFLoader/);
assert.match(layer,/MercatorCoordinate\.fromLngLat/);
assert.ok((landmarks.match(/model:'planned'/g)||[]).length>=10);
assert.doesNotMatch(app,/new THREE\.ExtrudeGeometry/);
console.log('stage2: PASS');
